# Generated by Django 5.0.6 on 2024-05-23 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shakes', '0003_shake_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shake',
            name='instructions',
            field=models.CharField(max_length=200),
        ),
    ]
