# Generated by Django 5.0.6 on 2024-05-25 22:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shakes', '0008_alter_shake_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shake',
            name='origin',
        ),
    ]
