# Generated by Django 5.0.6 on 2024-05-27 11:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shakes', '0011_shake_favourites'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shake',
            name='nutritional_info',
        ),
        migrations.RemoveField(
            model_name='shake',
            name='plan',
        ),
    ]
